# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-18 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='picture',
        ),
    ]
