# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-21 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_remove_tool_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='model_pic',
            field=models.ImageField(default='static/img/no-img.jpg', upload_to='static/img/'),
        ),
    ]
