# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-14 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_tool_model_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='model_pic',
            field=models.ImageField(default='/static/img/no-img.jpg', upload_to=''),
        ),
    ]
