# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-02-26 03:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0009_auto_20170226_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tools.Post'),
            preserve_default=False,
        ),
    ]
